apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: s3-creds
  namespace: kanister
data:
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  password: $KOPIA_PASSWORD
